#ifndef BLOCKPERSON_CONSTANTS_H
#define BLOCKPERSON_CONSTANTS_H

#define COLUMNS (SCREEN_WIDTH / TILE_SIZE)
#define GAME_SPEED 2
#define NUM_TILES_IN_ROW 32
#define ROWS (SCREEN_HEIGHT / TILE_SIZE)
#define TILE_SIZE 16

#endif //BLOCKPERSON_CONSTANTS_H
